import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/three">Three</Link>
        </li>
        <li>
          <Link to="/four">Four</Link>
        </li>
        <li>
          <Link to="/eleven">Eleven</Link>
        </li>
        <li>
          <Link to="/thirteen">Thirteen</Link>
        </li>
        <li>
          <Link to="/fourteen">Fourteen</Link>
        </li>
        <li>
          <Link to="/homepagedesktop">HomePageDesktop</Link>
        </li>
        <li>
          <Link to="/homepagelaptop">HomePageLaptop</Link>
        </li>
        <li>
          <Link to="/moviesshowspagedesktop">MoviesShowsPageDesktop</Link>
        </li>
        <li>
          <Link to="/moviesshowspagelaptop">MoviesShowsPageLaptop</Link>
        </li>
        <li>
          <Link to="/moviespageopendesktop">MoviesPageOpenDesktop</Link>
        </li>
        <li>
          <Link to="/moviespageopenlaptop">MoviesPageOpenLaptop</Link>
        </li>
        <li>
          <Link to="/showspageopendesktop">ShowsPageOpenDesktop</Link>
        </li>
        <li>
          <Link to="/showspageopenlaptop">ShowsPageOpenLaptop</Link>
        </li>
        <li>
          <Link to="/supportpagedesktop">SupportPageDesktop</Link>
        </li>
        <li>
          <Link to="/supportpagelaptop">SupportPageLaptop</Link>
        </li>
        <li>
          <Link to="/subscriptionpagedesktop">SubscriptionPageDesktop</Link>
        </li>
        <li>
          <Link to="/subscriptionpagelaptop">SubscriptionPageLaptop</Link>
        </li>
        <li>
          <Link to="/templateguide">TemplateGuide</Link>
        </li>
        <li>
          <Link to="/icons">Icons</Link>
        </li>
        <li>
          <Link to="/informationaboutthetemplate">
            InformationAboutTheTemplate
          </Link>
        </li>
        <li>
          <Link to="/nineteen">Nineteen</Link>
        </li>
        <li>
          <Link to="/ten">Ten</Link>
        </li>
        <li>
          <Link to="/seven">Seven</Link>
        </li>
        <li>
          <Link to="/twelve">Twelve</Link>
        </li>
        <li>
          <Link to="/fifteen">Fifteen</Link>
        </li>
        <li>
          <Link to="/six">Six</Link>
        </li>
        <li>
          <Link to="/eight">Eight</Link>
        </li>
        <li>
          <Link to="/seventeen">Seventeen</Link>
        </li>
        <li>
          <Link to="/nine">Nine</Link>
        </li>
        <li>
          <Link to="/sixteen">Sixteen</Link>
        </li>
        <li>
          <Link to="/eighteen">Eighteen</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/five">Five</Link>
        </li>
        <li>
          <Link to="/aboutus">AboutUs</Link>
        </li>
        <li>
          <Link to="/thumbnail">Thumbnail</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
